name: onewire39
favicon: null
layout_spectrum: 0.23215
typography_spectrum: 0.2371
title: 'Industrial Maintenance '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232426'
    - '#565a59'
    - '#919392'
    - '#f14038'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
