name: onewire39
favicon: null
layout_spectrum: 0.49207
typography_spectrum: 0.2371
title: 'Industrial Maintenance '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#ffffff'
    - '#bfb5a9'
    - '#6e6966'
    - '#c9def3'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
