name: onewire39
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25893
title: 'Industrial Maintenance '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89fdfc'
    - '#f2261f'
    - '#62575d'
    - '#7d0000'
    - '#be8493'
  brandStrength: 1
  lightness: 0
  saturation: 0.5036939084529877
  rhythmicContrast: 0.6790927045512944
purpose: []
