name: onewire39
favicon: null
layout_spectrum: 0.50397
typography_spectrum: 0.92361
title: 'Industrial Maintenance '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e1f24'
    - '#4f504b'
    - '#a56c63'
    - '#fcae63'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
